package com.tsuyu.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.CascadeType;

import com.tsuyu.model.User;

// default package
// Generated 11-Mar-2011 00:10:29 by Hibernate Tools 3.4.0.CR1

/**
 * SignIn generated by hbm2java
 */
@Entity
@Table(name = "sign_in", catalog = "tsuyu")
@org.hibernate.annotations.Entity(
		dynamicInsert = true,dynamicUpdate = true)
public class SignIn implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5802465026643739024L;
	private Integer signinId;
	private String userName;
	private String password;
	private User user;
	private AccessLevel accessLevel;

	public SignIn() {
	}

	public SignIn(String userName, String password) {
		this.userName = userName;
		this.password = password;
	}
	
	public SignIn(String userName, String password, User user, AccessLevel accessLevel) {
		this.userName = userName;
		this.password = password;
		this.user = user;
		this.accessLevel = accessLevel;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SIGNINID", unique = true, nullable = false)
	public Integer getSigninId() {
		return this.signinId;
	}

	public void setSigninId(Integer signinId) {
		this.signinId = signinId;
	}

	@Column(name = "USERNAME", nullable = false, length = 225)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "PASSWORD", nullable = false, length = 225)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	@OneToOne(fetch = FetchType.LAZY, mappedBy = "signIn")
	@org.hibernate.annotations.Cascade(value = {CascadeType.SAVE_UPDATE,CascadeType.DELETE})
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCESSLEVELID", nullable = false)
	public AccessLevel getAccessLevel() {
		return accessLevel;
	}

	public void setAccessLevel(AccessLevel accessLevel) {
		this.accessLevel = accessLevel;
	}


}
